# .github/workflows/release.yml

name: Release

on:
  push:
    branches:
      - main
env: 
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # - uses: actions/labeler@v4
    #   with:
    #     repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          ref: ${{ github.head_ref }}
          token: ${{ env.GITHUB_TOKEN }}

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Generate release
      if: success()
      run: npx semantic-release