# .github/workflows/release.yml

name: Release

on:
  push:
    branches:
      - main
env: 
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
          ref: ${{ github.head_ref }}
          token: ${{ env.GITHUB_TOKEN }}

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Generate release
      env:
        GIT_AUTHOR_NAME: "GitHub Actions"
        GIT_AUTHOR_EMAIL: "actions@github.com"
        GIT_COMMITTER_NAME: "GitHub Actions"
        GIT_COMMITTER_EMAIL: "actions@github.com"
        GH_TOKEN: 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
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        npx semantic-release