# .github/workflows/release.yml

name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # - uses: actions/labeler@v4
    #   with:
    #     repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          ref: ${{ github.head_ref }}
          token: ${{ env.GITHUB_TOKEN }}

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Generate release
      env:
        GIT_AUTHOR_NAME: "GitHub Actions"
        GIT_AUTHOR_EMAIL: "actions@github.com"
        GIT_COMMITTER_NAME: "GitHub Actions"
        GIT_COMMITTER_EMAIL: "actions@github.com"
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        npx semantic-release